import Head from 'next/head';
import SearchBar from '../components/SearchBar';
import Coins from '../components/Coins';
import { apiUrl } from '../utils/constants';

export default function Home({ filteredCoins }) {
    return (
        <div>
            <Head>
                <title>Crypto Tracker</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SearchBar type="text" placeholder="Search" />
            <Coins />
        </div>
    )
}

export const getServerSideProps = async () => {
    const res = await fetch(apiUrl);

    const filteredCoins = await res.json();

    return { props: { filteredCoins } };
}